### PR TITLE
new branch

### PR DESCRIPTION
**Pull request by Jegelewicz**
I am experimenting with a branch to your ixodes code.

### CODE REVIEW

**Comment by njdowdy** [comment]
Hey Teresa! I think a "pull request" is the request that's made to tell the repository owner that you think your version of the code should be merged with the "main" (or some other) branch (I could be wrong though!). I made a separate branch called "teresa". Can you try to pull that branch, change something, and then commit and push changes to that branch? I think that's what we want. Then, if we determine the "teresa" branch to be superior, we can merge that branch onto "main". Sorry if I have the details on this incorrect!

EDIT: Just adding that everything on my end is saying this action will merge changes onto "njdowdy:main", which is what we were trying to avoid for now.

**Comment by Jegelewicz** [comment]
I am still not sure about this process, but it does appear that I am working in my own branch - I will refrain from pull requests for now!

**Comment by Jegelewicz** [comment]
@njdowdy I think I found code to remove all begin and end trailing whitespace as well as encoding. It is in my branch and I have tested it, but maybe you can try it too?

```
# strip spaces from start and ends of strings
library(data.table)
setDT(df)
cols_to_be_rectified <- names(df)[vapply(df, is.character, logical(1))]
df[,c(cols_to_be_rectified) := lapply(.SD, trimws), .SDcols = cols_to_be_rectified]

# remove remove '\xa0' chars
setDT(df)
cols_to_be_rectified <- names(df)[vapply(df, is.character, logical(1))]
df[,c(cols_to_be_rectified) := lapply(.SD, removeEncoding), .SDcols = cols_to_be_rectified]```

**Comment by Jegelewicz** [comment]
Because copy-paste is how I get code done....

**Pull request closed without merging**
